sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/139ee9cb81579bfd2517
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
node_js:
  - '6'
  - '5'
  - '4'
before_install:
  - npm i -g gulp
before_script:
  - npm prune
after_success:
  - npm run release
branches:
  except:
    - /^(v\d+\.\d+\.\d+)|gh-pages$/
